name: run service.py

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: checkout repo content
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3
          pip install bs4
          pip install requests
      - name: execute logo script # run service.py
        run: python -c "import os; os.chdir('.epg'); import make_logos"     
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "new tvs-logos"
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      - name: Run EPG Generator
        run: python -c "import os; os.chdir('.epg'); import make_guide"     

      - name: Set date tag
        run: echo "TAG=v$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Upload XML + GZ as release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: "EPG ${{ env.TAG }}"
          body: "Automated daily EPG update."
          files: |
            guide.xml
            guide.xml.gz
            maclist.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token:  ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
