name: run service.py

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: checkout repo content
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3
          pip install bs4
          pip install requests
      - name: execute logo script # run service.py
        run: python -c "import os; os.chdir('.epg'); import make_logos"     
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "new tvs-logos"
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      - name: Run EPG Generator
        run: python -c "import os; os.chdir('.epg'); import make_guide"     

      - name: Upload XML + GZ as release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: EPG
          name: "DAILY EPG"
          body: "Automated daily EPG update."
          files: |
            guide.xml
            guide.xml.gz
            maclist.json
            xstreamlist.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          releases_keep_latest: 1
          delete_workflows: true
          workflows_keep_day: 1
          delete_tags: true
          gh_token: ${{ secrets.GITHUB_TOKEN }}
